version: '2'
services:
    santamaria-app:
        image: santamaria
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://santamaria-postgresql:5432/santamaria
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    santamaria-postgresql:
        extends:
            file: postgresql.yml
            service: santamaria-postgresql
